# Generated by Django 3.1.2 on 2020-10-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lotte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('p_id', models.CharField(max_length=1000)),
                ('p_detail_url', models.CharField(max_length=1000)),
                ('p_detail_inner_url', models.CharField(max_length=1000)),
                ('p_thumb_url', models.CharField(max_length=1000)),
                ('p_brand', models.CharField(max_length=1000)),
                ('p_name', models.CharField(max_length=1000)),
                ('p_price', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
